// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: languages.sql

package database

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages(id, name)
VALUES(gen_random_uuid(), $1)
returning id, name
`

func (q *Queries) CreateLanguage(ctx context.Context, name string) (Language, error) {
	row := q.db.QueryRowContext(ctx, createLanguage, name)
	var i Language
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
